#print("My Name is :- Piyush More")
print("college :- k.k.wagh,poly")
print("Address :- dhule road ,chalisgaon")
print("Age :- 18")
a=int(input("enter no"))
b=int(input("enter 2no"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)