a = int(input("Enter First number: "))
b = int(input("Enter Second number: "))

print(f"Addition of {a} and {b}: {a+b}")
print(f"Subtraction of {a} and {b}: {a-b}")
print(f"Multiplication of {a} and {b}: {a*b}")
print(f"Division of {a} and {b}: {a/b}")
print(f"Floor division {a} and {b}: {a//b}")
print(f"Modulus of{a} and {b}: {a%b}")
print(f"Exponentiation of {a} and {b}: {a**b}")